FROM nginx:1.25

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf.template /etc/nginx/templates/
RUN mkdir -p /etc/nginx/includes

COPY ./ssl /etc/ssl

COPY nginx-entrypoint.sh /docker-entrypoint.d