services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn tron_viewer.main:app --host 0.0.0.0
    volumes:
      - ./app:/usr/src/tron_viewer
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      dev-db:
        condition: service_healthy
        restart: true

  dev-db:
    image: postgres:15
    env_file:
      - .env.dev
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=dev-pwd123
      - POSTGRES_DB=dev-database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev-user -d dev-database"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_db:
