services:
  viewer:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: uvicorn tron_viewer.main:app --host 0.0.0.0 --port 8000 --workers 4
    volumes:
      - ./app:/usr/src/tron_viewer
    env_file:
      - .env.prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
        restart: true
    healthcheck:
      test: curl --fail http://localhost:8000/docs || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 3s

  db:
    image: postgres:15
    env_file:
      - .env.prod
    volumes:
      - tron_db_volume:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tron-db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  web:
    build: 
      context: .
      dockerfile: ./Dockerfile.nginx
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      viewer:
        condition: service_healthy
        restart: true


volumes:
  tron_db_volume:
